/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { AppGenByocDataClient } from '../common/byoc-sdk-data-client';
import { CommonDataSourceOperations } from '../common/common-data-source-operations';
import type {
  ChoiceColumnToTypescriptMapping,
  ColumnToTypescriptMapping,
  LookupColumnToTypescriptMapping,
  TableToTypescriptMapping,
} from '../common/table-mapping-types';
import { getTargetTableMetadata } from '../common/table-metadata-utils';
import type { TableCell, TableRow } from '../common/types';
import {
  formatAsSharePointLookup,
  formatSharePointChoiceApiToDataSource,
  formatSharePointChoiceForApi,
  formatSharePointChoicesAsStringArray,
  formatSharePointChoicesForApi,
  mapSharePointLookupApiCellToDataSourceCell,
} from './sharepoint-formatters';
import { toSharePointLookupIdPropertyName } from './sharepoint-utils';

/**
 * Strips specified fields from a SharePoint record.
 */
function stripFields(record: TableRow, fieldsToStrip: string[]): TableRow {
  const result = { ...record };
  for (const field of fieldsToStrip) {
    delete result[field];
  }
  return result;
}

/**
 * SharePoint-specific BYOC client configuration.
 * - Uses dataSourceKey as table identifier (SharePoint list identifier)
 * - Strips ID fields on create/update (SharePoint auto-generates IDs)
 */
const sharePointClientConfig = {
  getTableId: (tableMetadata: TableToTypescriptMapping): string =>
    tableMetadata.dataSourceKey,
  sanitizeRecordOnCreate: (record: TableRow): TableRow =>
    stripFields(record, ['id', 'ID', 'Id']),
  sanitizeRecordOnUpdate: (record: TableRow): TableRow =>
    stripFields(record, ['id', 'ID', 'Id', 'ItemInternalId']),
};

// SharePoint data source operations using the BYOC SDK client (Power Apps Data SDK)
export const sharePointDataSourceOperations = new CommonDataSourceOperations({
  dataClient: new AppGenByocDataClient(sharePointClientConfig),
  isValidRecordId: (recordId: string) =>
    /^\d+$/.test(recordId) && parseInt(recordId, 10) > 0,
  mapApiRowToDataSourceRowOptions: {
    // SharePoint API returns properties in their original case (PascalCase),
    // but our mappings may store lowercase property names. Use case-insensitive lookup.
    getApiRowValue: ({
      apiRow,
      cellKey,
      column,
    }: {
      apiRow: TableRow;
      cellKey: string;
      column: ColumnToTypescriptMapping;
    }): TableCell => {
      // Try exact match first
      if (cellKey in apiRow) {
        return apiRow[cellKey] as TableCell;
      }

      // Try case-sensitive property name if different from cellKey
      if (
        column.apiPropertyNameCaseSensitive &&
        column.apiPropertyNameCaseSensitive !== cellKey &&
        column.apiPropertyNameCaseSensitive in apiRow
      ) {
        return apiRow[column.apiPropertyNameCaseSensitive] as TableCell;
      }

      // Fall back to case-insensitive lookup
      const lowerCellKey = cellKey.toLowerCase();
      const matchingKey = Object.keys(apiRow).find(
        (key) => key.toLowerCase() === lowerCellKey,
      );
      if (matchingKey) {
        return apiRow[matchingKey] as TableCell;
      }

      return undefined;
    },
    customFormatters: {
      // SharePoint returns ID as number (Counter type), but UI expects string (for .trim() etc.)
      // Convert primary ID column to string
      Integer: async (options): Promise<TableCell> => {
        if (
          options.column.isPrimaryId &&
          typeof options.tableCell === 'number'
        ) {
          return Promise.resolve(options.tableCell.toString());
        }
        return Promise.resolve(options.tableCell as TableCell);
      },
      Choice: async (options): Promise<TableCell> => {
        const choiceColumn = options.column as ChoiceColumnToTypescriptMapping;
        return Promise.resolve(
          formatSharePointChoiceApiToDataSource(
            options.tableMetadata,
            choiceColumn,
            options.tableCell,
          ) as TableCell,
        );
      },
      Choices: async (options): Promise<TableCell> => {
        const choiceColumn = options.column as ChoiceColumnToTypescriptMapping;
        return Promise.resolve(
          formatSharePointChoicesAsStringArray(
            options.tableMetadata,
            choiceColumn,
            options.tableCell,
          ) as TableCell,
        );
      },
      Lookup: async (options): Promise<TableCell> => {
        const lookupColumn = options.column as LookupColumnToTypescriptMapping;
        return (await mapSharePointLookupApiCellToDataSourceCell({
          column: lookupColumn,
          tableCell: options.tableCell,
          row: options.row,
        })) as TableCell;
      },
    },
    getCustomApiPropertyName: {
      Lookup: (options): string => {
        return toSharePointLookupIdPropertyName(options.column.apiPropertyName);
      },
    },
  },
  mapDataSourceRowToApiRowOptions: {
    customFormatters: {
      Choice: async (options): Promise<TableCell> => {
        const choiceColumn = options.column as ChoiceColumnToTypescriptMapping;
        return Promise.resolve(
          formatSharePointChoiceForApi(
            options.tableMetadata,
            choiceColumn,
            options.tableCell,
          ) as TableCell,
        );
      },
      Choices: async (options): Promise<TableCell> => {
        const choiceColumn = options.column as ChoiceColumnToTypescriptMapping;
        return Promise.resolve(
          formatSharePointChoicesForApi(
            options.tableMetadata,
            choiceColumn,
            options.tableCell,
            false, // Use modern REST API format, not legacy
          ) as TableCell,
        );
      },
      Lookup: async (options): Promise<TableCell> => {
        const lookupColumn = options.column as LookupColumnToTypescriptMapping;
        return Promise.resolve(
          (await formatAsSharePointLookup(
            options.tableMetadata,
            lookupColumn,
            options.tableCell,
          )) as TableCell,
        );
      },
    },
    getCustomOutputApiPropertyName: {
      Lookup: (options): string => {
        return toSharePointLookupIdPropertyName(options.column.apiPropertyName);
      },
    },
  },

  convertRetrieveAllOptionsFromTypescriptToApiOptions: {
    // Convert TypeScript filter expressions to SharePoint OData filter format
    convertFilterAsync: async (
      tableMetadata: TableToTypescriptMapping,
      filter: string,
    ): Promise<string> => {
      for (const columnMapping of tableMetadata.columns) {
        if (columnMapping.type === 'Lookup') {
          const lookupColumn = columnMapping as LookupColumnToTypescriptMapping;
          const targetTable = await getTargetTableMetadata({
            targetTableApiMetadataTableId:
              lookupColumn.lookupMetadata.targetTableApiMetadataTableId,
          });

          // Lookup Primary Id - SharePoint uses <FieldName>Id format
          filter = filter.replace(
            `${columnMapping.typescriptPropertyName}/${targetTable.primaryIdColumnMapping.typescriptPropertyName}`,
            toSharePointLookupIdPropertyName(lookupColumn.apiPropertyName),
          );

          // Lookup Primary Name - SharePoint uses <FieldName>/Title format for expanded lookups
          filter = filter.replace(
            `${columnMapping.typescriptPropertyName}/${targetTable.primaryNameColumnMapping.typescriptPropertyName}`,
            `${lookupColumn.apiPropertyName}/${targetTable.primaryNameColumnMapping.apiPropertyName}`,
          );
        } else if (
          columnMapping.type === 'Choices' ||
          columnMapping.type === 'Choice'
        ) {
          const choiceColumn = columnMapping as ChoiceColumnToTypescriptMapping;
          for (const option of choiceColumn.optionSetMetadata.options) {
            const apiValueFormatted =
              typeof option.apiValue === 'string'
                ? `'${option.apiValue}'`
                : option.apiValue;
            filter = filter.replace(
              `'${option.typescriptValue}'`,
              `${apiValueFormatted.toString()}`,
            );
          }
        }

        // Convert all TypeScript property names to SharePoint API property names in filter
        // Escape special regex characters in the property name
        const escapedPropertyName =
          columnMapping.typescriptPropertyName.replace(
            /[.*+?^${}()|[\]\\]/g,
            '\\$&',
          );
        // eslint-disable-next-line security/detect-non-literal-regexp
        const regex = new RegExp(`\\b${escapedPropertyName}\\b`, 'g');
        filter = filter.replace(regex, columnMapping.apiPropertyName);
      }
      return filter;
    },

    // Convert TypeScript orderBy expressions to SharePoint OData orderby format
    convertOrderByAsync: async (
      tableMetadata: TableToTypescriptMapping,
      orderBy: string[],
    ): Promise<string[]> => {
      const updatedOrderBy: string[] = [];

      for (let orderByEntry of orderBy) {
        for (const columnMapping of tableMetadata.columns) {
          if (columnMapping.type === 'Lookup') {
            const lookupColumn =
              columnMapping as LookupColumnToTypescriptMapping;
            const targetTable = await getTargetTableMetadata({
              targetTableApiMetadataTableId:
                lookupColumn.lookupMetadata.targetTableApiMetadataTableId,
            });

            // Lookup Primary Id - SharePoint uses <FieldName>Id format
            orderByEntry = orderByEntry.replace(
              `${columnMapping.typescriptPropertyName}/${targetTable.primaryIdColumnMapping.typescriptPropertyName}`,
              toSharePointLookupIdPropertyName(lookupColumn.apiPropertyName),
            );

            // Lookup Primary Name - SharePoint uses <FieldName>/Title format for expanded lookups
            orderByEntry = orderByEntry.replace(
              `${columnMapping.typescriptPropertyName}/${targetTable.primaryNameColumnMapping.typescriptPropertyName}`,
              `${lookupColumn.apiPropertyName}/${targetTable.primaryNameColumnMapping.apiPropertyName}`,
            );
          }

          // Convert TypeScript property name to SharePoint API property name
          const escapedPropertyName =
            columnMapping.typescriptPropertyName.replace(
              /[.*+?^${}()|[\]\\]/g,
              '\\$&',
            );
          // eslint-disable-next-line security/detect-non-literal-regexp
          const regex = new RegExp(`\\b${escapedPropertyName}\\b`, 'g');
          orderByEntry = orderByEntry.replace(
            regex,
            columnMapping.apiPropertyName,
          );
        }
        updatedOrderBy.push(orderByEntry);
      }

      return updatedOrderBy;
    },
  },
});
