/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import {
  getTableAndColumnEventData,
  logWarning,
} from '../common/logger-client';
import type {
  ChoiceColumnToTypescriptMapping,
  LookupColumnToTypescriptMapping,
  TableToTypescriptMapping,
} from '../common/table-mapping-types';
import {
  getPrimaryNameColumn,
  getTableMetadata,
} from '../common/table-metadata-utils';
import type {
  IAppGenDataClient,
  NotNullOrUndefinedTableCell,
  TableCell,
  TableRow,
} from '../common/types';

interface MapSharePointLookupApiCellToDataSourceCellOptions {
  column: LookupColumnToTypescriptMapping;
  tableCell: NotNullOrUndefinedTableCell;
  row: TableRow;
}

/**
 * Maps a SharePoint lookup field from API format to TypeScript data source format.
 * SharePoint lookups come back as objects with Id and Title properties (or the custom name field).
 */
export async function mapSharePointLookupApiCellToDataSourceCell(
  options: MapSharePointLookupApiCellToDataSourceCellOptions,
): Promise<TableCell | undefined> {
  const { column, tableCell, row } = options;

  const lookupIdField = `${column.apiPropertyName}Id`;
  const lookupTitleField = `${column.apiPropertyName}Title`;

  let lookupId: number | undefined;
  let lookupTitle: string | undefined;

  // Try to get lookup data from different possible formats
  if (typeof tableCell === 'object' && tableCell !== null) {
    const lookupObj = tableCell as Record<string, unknown>;
    lookupId = lookupObj.Id as number;
    lookupTitle = (lookupObj.Value ?? lookupObj.Title) as string;
  } else if (row[lookupIdField]) {
    lookupId = row[lookupIdField] as number;
    lookupTitle = row[lookupTitleField] as string;
  } else if (typeof tableCell === 'number') {
    lookupId = tableCell;
  }

  if (!lookupId) {
    return undefined;
  }

  const targetTableMetadata = await getTableMetadata({
    apiMetadataTableId: column.lookupMetadata.targetTableApiMetadataTableId,
  });

  const targetTablePrimaryIdColumnLogicalName =
    targetTableMetadata.columns.find((x) => x.isPrimaryId)?.apiPropertyName ||
    'ID';
  const targetTablePrimaryNameColumnLogicalName =
    getPrimaryNameColumn(targetTableMetadata)?.apiPropertyName || 'Title';

  // Convert lookupId to string for UI compatibility (UI code expects string IDs like Dataverse)
  return {
    [targetTablePrimaryIdColumnLogicalName]: lookupId.toString(),
    [targetTablePrimaryNameColumnLogicalName]: lookupTitle || '',
  };
}

interface MapSharePointLookupApiCellToDataSourceCellWithDataClientOptions {
  column: LookupColumnToTypescriptMapping;
  tableCell: NotNullOrUndefinedTableCell;
  row: TableRow;
  dataClient: IAppGenDataClient;
}

/**
 * Maps a SharePoint lookup field with data fetching if title is missing.
 * This version fetches the lookup item data if it's not already expanded.
 */
export async function mapSharePointLookupApiCellToDataSourceCellWithDataClient(
  options: MapSharePointLookupApiCellToDataSourceCellWithDataClientOptions,
): Promise<TableCell | undefined> {
  const { column, tableCell, row, dataClient } = options;

  const lookupIdField = `${column.apiPropertyName}Id`;
  let lookupId: number | undefined;

  if (typeof tableCell === 'object' && tableCell !== null) {
    const lookupObj = tableCell as Record<string, unknown>;
    lookupId = lookupObj.Id as number;
  } else if (row[lookupIdField]) {
    lookupId = row[lookupIdField] as number;
  } else if (typeof tableCell === 'number') {
    lookupId = tableCell;
  }

  if (!lookupId) {
    return undefined;
  }

  const targetTableMetadata = await getTableMetadata({
    apiMetadataTableId: column.lookupMetadata.targetTableApiMetadataTableId,
  });

  const targetTablePrimaryIdColumnLogicalName =
    targetTableMetadata.columns.find((x) => x.isPrimaryId)?.apiPropertyName ||
    'ID';
  const targetTablePrimaryNameColumnLogicalName =
    getPrimaryNameColumn(targetTableMetadata)?.apiPropertyName || 'Title';

  // Fetch the lookup item to get the title
  try {
    const lookupItem = await dataClient.retrieveRecordAsync(
      targetTableMetadata,
      lookupId.toString(),
    );

    // Convert lookupId to string for UI compatibility (UI code expects string IDs like Dataverse)
    return {
      [targetTablePrimaryIdColumnLogicalName]: lookupId.toString(),
      [targetTablePrimaryNameColumnLogicalName]:
        lookupItem[targetTablePrimaryNameColumnLogicalName] || '',
    };
  } catch (error) {
    logWarning('mapSharePointLookupApiCellToDataSourceCellWithDataClient', {
      type: 'LookupItemFetchFailed',
      data: {
        ...getTableAndColumnEventData(targetTableMetadata, column),
        lookupId,
        error: error instanceof Error ? error.message : String(error),
      },
    });

    // Return with just the ID if fetch fails - convert to string for UI compatibility
    return {
      [targetTablePrimaryIdColumnLogicalName]: lookupId.toString(),
      [targetTablePrimaryNameColumnLogicalName]: '',
    };
  }
}

/**
 * Formats a TypeScript lookup value to SharePoint API format for create/update.
 * SharePoint connector expects lookup values as an object with Id property.
 *
 * TypeScript format: { id: 1, title: "Item Name" }
 * API format: { Id: 1, Value: "Item Name" } or { Id: 1 }
 */
export async function formatAsSharePointLookup(
  tableMetadata: TableToTypescriptMapping,
  column: LookupColumnToTypescriptMapping,
  rowData: NotNullOrUndefinedTableCell,
): Promise<{ Id: number; Value?: string } | undefined> {
  const anyRowData = rowData as Record<string, unknown>;

  // Try different possible ID property names
  // SharePoint uses "ID" (uppercase), but we also check lowercase variations for compatibility
  const idProp = column.lookupMetadata.targetTableApiMetadataTableId + 'id';
  const idPropUppercase =
    column.lookupMetadata.targetTableApiMetadataTableId + 'Id';

  const lookupId =
    anyRowData?.[idProp] ||
    anyRowData?.[idPropUppercase] ||
    anyRowData?.id ||
    anyRowData?.Id ||
    anyRowData?.ID; // SharePoint standard uppercase ID

  if (!lookupId) {
    return undefined;
  }

  // SharePoint expects numeric IDs
  const numericId =
    typeof lookupId === 'number' ? lookupId : parseInt(String(lookupId), 10);

  if (Number.isNaN(numericId)) {
    logWarning('formatAsSharePointLookup', {
      type: 'InvalidLookupIdFormat',
      data: {
        ...getTableAndColumnEventData(tableMetadata, column),
        lookupId: String(lookupId),
      },
    });
    return undefined;
  }

  // SharePoint connector expects lookup as object with Id property
  // Try to also include Value if available for better compatibility
  const lookupValue =
    anyRowData?.Value ||
    anyRowData?.value ||
    anyRowData?.Title ||
    anyRowData?.title;

  if (lookupValue && typeof lookupValue === 'string') {
    return { Id: numericId, Value: lookupValue };
  }

  return { Id: numericId };
}

/**
 * Formats a TypeScript single-choice value to SharePoint API format for create/update.
 * SharePoint connector expects single Choice values as an object with Value property.
 */
export function formatSharePointChoiceForApi(
  tableMetadata: TableToTypescriptMapping,
  column: ChoiceColumnToTypescriptMapping,
  tableCell: NotNullOrUndefinedTableCell,
): { Value: string } | string | undefined {
  if (tableCell === null || tableCell === undefined) {
    return undefined;
  }

  // If it's already a string, validate against known options and return as object
  if (typeof tableCell === 'string') {
    const trimmedValue = tableCell.trim();

    if (!trimmedValue) {
      return undefined;
    }

    // Find matching option by label or API value
    const lowercaseValue = trimmedValue.toLowerCase();
    const option = column.optionSetMetadata.options.find((x) => {
      return (
        x.label.toLowerCase().trim() === lowercaseValue ||
        String(x.apiValue).toLowerCase().trim() === lowercaseValue
      );
    });

    if (option) {
      return { Value: String(option.apiValue) };
    }

    // If no matching option found, log warning but still try to use the value
    logWarning('formatSharePointChoiceForApi', {
      type: 'UnmappedChoiceValue',
      data: {
        ...getTableAndColumnEventData(tableMetadata, column),
        providedValue: trimmedValue,
      },
    });

    // Return as object anyway - SharePoint will validate
    return { Value: trimmedValue };
  }

  logWarning('formatSharePointChoiceForApi', {
    type: 'InvalidChoiceValueType',
    data: {
      ...getTableAndColumnEventData(tableMetadata, column),
      receivedType: typeof tableCell,
    },
  });

  return undefined;
}

/**
 * Formats a SharePoint multi-choice field from API string to TypeScript array format.
 * SharePoint returns multi-choice as semicolon-separated string with "#" delimiters.
 */
export function formatSharePointChoicesAsStringArray(
  tableMetadata: TableToTypescriptMapping,
  column: ChoiceColumnToTypescriptMapping,
  tableCell: NotNullOrUndefinedTableCell,
): TableCell {
  if (typeof tableCell !== 'string') {
    logWarning('formatSharePointChoicesAsStringArray', {
      type: 'InvalidChoiceValueType',
      data: getTableAndColumnEventData(tableMetadata, column),
    });
    return tableCell;
  }

  // SharePoint multi-choice format: ";#Choice1;#Choice2;#"
  // Remove leading/trailing ";#" and split by ";#"
  const cleanedValue = tableCell.replace(/^;#/, '').replace(/;#$/, '');

  if (!cleanedValue) {
    return [];
  }

  return cleanedValue
    .split(';#')
    .map((item) => item.trim())
    .filter((item) => item.length > 0);
}

/**
 * Formats a TypeScript multi-choice array to SharePoint API format.
 * SharePoint expects semicolon-separated string with "#" delimiters or JSON array for REST API.
 */
export function formatSharePointChoicesForApi(
  tableMetadata: TableToTypescriptMapping,
  column: ChoiceColumnToTypescriptMapping,
  tableCell: NotNullOrUndefinedTableCell,
  useLegacyFormat: boolean = false,
): TableCell {
  // Handle array input (most common case for multi-select)
  if (Array.isArray(tableCell)) {
    const results: string[] = [];
    const unmappedChoiceValues: string[] = [];

    for (const item of tableCell) {
      if (item === null || item === undefined) {
        continue;
      }

      const itemAsString = String(item);
      const lowercaseItem = itemAsString.toLowerCase().trim();

      // Find matching option by label or API value
      const option = column.optionSetMetadata.options.find((x) => {
        return (
          x.label.toLowerCase().trim() === lowercaseItem ||
          String(x.apiValue).toLowerCase().trim() === lowercaseItem
        );
      });

      if (option) {
        // Use the label for SharePoint (not the numeric value)
        results.push(String(option.apiValue));
      } else {
        unmappedChoiceValues.push(lowercaseItem);
      }
    }

    if (unmappedChoiceValues.length > 0) {
      logWarning('formatSharePointChoicesForApi', {
        type: 'UnmappedChoicesValues',
        data: {
          ...getTableAndColumnEventData(tableMetadata, column),
          unmappedChoiceValues: unmappedChoiceValues.join(','),
        },
      });
    }

    if (results.length === 0) {
      return null;
    }

    if (useLegacyFormat) {
      // Legacy format: ";#Choice1;#Choice2;#"
      return `;#${results.join(';#')};#`;
    } else {
      // Modern format: { results: [...] }
      return { results };
    }
  } else {
    logWarning('formatSharePointChoicesForApi', {
      type: 'InvalidChoiceValueType',
      data: getTableAndColumnEventData(tableMetadata, column),
    });
  }

  return undefined;
}

/**
 * Formats a SharePoint single-choice field from API to TypeScript format.
 * Single choice comes as a simple string value.
 */
export function formatSharePointChoiceAsString(
  tableMetadata: TableToTypescriptMapping,
  column: ChoiceColumnToTypescriptMapping,
  tableCell: NotNullOrUndefinedTableCell,
): string | undefined {
  if (typeof tableCell !== 'string') {
    logWarning('formatSharePointChoiceAsString', {
      type: 'InvalidChoiceValueType',
      data: getTableAndColumnEventData(tableMetadata, column),
    });
    return undefined;
  }

  return tableCell.trim();
}

/**
 * Interface for SharePoint SPListExpandedReference (Choice/Lookup expanded objects)
 */
interface SPListExpandedReference {
  '@odata.type'?: string;
  Id?: number;
  Value?: string;
}

/**
 * Formats a SharePoint single-choice field from API to data source format.
 * SharePoint REST API returns Choice fields as SPListExpandedReference objects when expanded.
 */
export function formatSharePointChoiceApiToDataSource(
  tableMetadata: TableToTypescriptMapping,
  column: ChoiceColumnToTypescriptMapping,
  tableCell: NotNullOrUndefinedTableCell,
): string | undefined {
  // Handle simple string value (non-expanded)
  if (typeof tableCell === 'string') {
    return tableCell.trim();
  }

  // Handle SPListExpandedReference object (expanded choice)
  if (typeof tableCell === 'object' && tableCell !== null) {
    const expandedRef = tableCell as SPListExpandedReference;
    if (expandedRef.Value !== undefined) {
      return String(expandedRef.Value).trim();
    }

    logWarning('formatSharePointChoiceApiToDataSource', {
      type: 'MissingValueInExpandedReference',
      data: {
        ...getTableAndColumnEventData(tableMetadata, column),
        receivedKeys: Object.keys(tableCell).join(','),
      },
    });
    return undefined;
  }

  logWarning('formatSharePointChoiceApiToDataSource', {
    type: 'InvalidChoiceValueType',
    data: {
      ...getTableAndColumnEventData(tableMetadata, column),
      receivedType: typeof tableCell,
    },
  });
  return undefined;
}
