/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

/**
 * Returns the SharePoint lookup field property name for API operations.
 * @example toSharePointLookupIdPropertyName("Customer") // "Customer"
 */
export function toSharePointLookupIdPropertyName(
  fieldInternalName: string,
): string {
  return `${fieldInternalName}`;
}

/**
 * Returns the lookup title property name.
 * @example toSharePointLookupTitlePropertyName("Customer") // "CustomerTitle"
 */
export function toSharePointLookupTitlePropertyName(
  fieldInternalName: string,
): string {
  return `${fieldInternalName}Title`;
}

/**
 * Extracts item ID from a SharePoint REST API URL.
 * @example extractSharePointItemId("_api/web/lists(guid'...')/items(123)") // "123"
 */
export function extractSharePointItemId(value: string): string | null {
  const match = value.match(/items\((\d+)\)/);
  return match ? match[1] : null;
}

/**
 * Extracts list GUID from a SharePoint REST API URL.
 * @example extractSharePointListId("_api/web/lists(guid'abc-123')") // "abc-123"
 */
export function extractSharePointListId(value: string): string | null {
  const match = value.match(/lists\(guid'([^']+)'\)/);
  return match ? match[1] : null;
}

/**
 * Formats a SharePoint list item reference URL.
 * @example formatSharePointItemReference("abc-123", 456) // "_api/web/lists(guid'abc-123')/items(456)"
 */
export function formatSharePointItemReference(
  listId: string,
  itemId: number | string,
): string {
  return `_api/web/lists(guid'${listId}')/items(${itemId})`;
}

/**
 * Parses SharePoint legacy multi-choice format (";#Choice1;#Choice2;#") to array.
 * @example parseSharePointMultiChoiceValue(";#Red;#Blue;#") // ["Red", "Blue"]
 */
export function parseSharePointMultiChoiceValue(value: string): string[] {
  if (!value || typeof value !== 'string') {
    return [];
  }

  const cleanedValue = value.replace(/^;#/, '').replace(/;#$/, '');
  if (!cleanedValue) {
    return [];
  }

  return cleanedValue
    .split(';#')
    .map((item) => item.trim())
    .filter((item) => item.length > 0);
}

/**
 * Formats array to SharePoint legacy multi-choice format.
 * @example formatSharePointMultiChoiceValue(["Red", "Blue"]) // ";#Red;#Blue;#"
 */
export function formatSharePointMultiChoiceValue(choices: string[]): string {
  if (!Array.isArray(choices) || choices.length === 0) {
    return '';
  }
  return `;#${choices.join(';#')};#`;
}

/**
 * Parses SharePoint person field value ("id;#Display Name" format).
 * @example parseSharePointPersonValue("123;#John Doe") // { id: 123, displayName: "John Doe" }
 */
export function parseSharePointPersonValue(
  value: string,
): { id: number; displayName: string } | null {
  if (!value || typeof value !== 'string') {
    return null;
  }

  const match = value.match(/^(\d+);#(.+)$/);
  if (!match) {
    return null;
  }

  return {
    id: parseInt(match[1], 10),
    displayName: match[2],
  };
}

/**
 * Converts user ID to numeric format for SharePoint API.
 * @throws Error if userId is not a valid number
 */
export function formatSharePointPersonValue(userId: number | string): number {
  const numericId =
    typeof userId === 'number' ? userId : parseInt(String(userId), 10);
  if (Number.isNaN(numericId)) {
    throw new Error(`Invalid user ID: ${userId}`);
  }
  return numericId;
}

/**
 * Checks if a field is a SharePoint system/reserved field.
 */
export function isSharePointSystemField(internalName: string): boolean {
  const systemFields = [
    'ContentType',
    'ContentTypeId',
    '_ModerationStatus',
    'Edit',
    'Type',
    'CheckoutUser',
    'CheckedOutUserId',
    'IsCheckedoutToLocal',
    'ServerRedirectedEmbedUrl',
    'ServerRedirectedEmbedUri',
    'FileLeafRef',
    'FileDirRef',
    'FSObjType',
    'PermMask',
    'PrincipalCount',
    'FileRef',
    'File_x0020_Type',
    'HTML_x0020_File_x0020_Type',
    'UniqueId',
    'SyncClientId',
    'ProgId',
    'ScopeId',
    'VirusStatus',
    'CheckedOutTitle',
    '_CheckinComment',
    'LinkCheckedOutTitle',
    '_EditMenuTableStart',
    '_EditMenuTableEnd',
    'LinkFilenameNoMenu',
    'LinkFilename',
    'DocIcon',
    'FileSizeDisplay',
    'ItemChildCount',
    'FolderChildCount',
    'Restricted',
    '_SourceUrl',
    '_SharedFileIndex',
    'AppAuthor',
    'AppEditor',
    'ComplianceAssetId',
    '_ComplianceFlags',
    '_ComplianceTag',
    '_ComplianceTagWrittenTime',
    '_ComplianceTagUserId',
  ];

  return (
    systemFields.includes(internalName) ||
    (internalName.startsWith('_') && internalName !== '_UIVersionString')
  );
}

/**
 * Encodes display name to SharePoint internal name format.
 * @example toSharePointInternalName("My Field") // "My_x0020_Field"
 */
export function toSharePointInternalName(displayName: string): string {
  return displayName.replace(/ /g, '_x0020_');
}

/**
 * Decodes SharePoint internal name to display name.
 * @example fromSharePointInternalName("My_x0020_Field") // "My Field"
 */
export function fromSharePointInternalName(internalName: string): string {
  return internalName
    .replace(/_x0020_/g, ' ')
    .replace(/_x005f_/g, '_')
    .replace(/_x002d_/g, '-')
    .replace(/_x0028_/g, '(')
    .replace(/_x0029_/g, ')');
}

/**
 * Validates if a string is a valid GUID format.
 */
export function isValidSharePointListGuid(value: string): boolean {
  const guidRegex =
    /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/;
  return guidRegex.test(value);
}
