/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import type {
  ConvertToDataSourceInfoResult,
  DataSourceInfoGenerator,
} from '../common/data-source-info-generator';
import type { TableToTypescriptMapping } from '../common/table-mapping-types';

class SharePointDataSourceInfoGenerator implements DataSourceInfoGenerator {
  public convertToDataSourceInfo(
    tableMapping: TableToTypescriptMapping,
  ): ConvertToDataSourceInfoResult | undefined {
    return {
      key: tableMapping.dataSourceKey,
      info: {
        tableId: tableMapping.apiDataTableId || '',
        version: '',
        primaryKey:
          tableMapping.columns.find((x) => x.isPrimaryId)?.apiPropertyName ||
          'ID',
        dataSourceType: 'Connector',
        apis: {},
      },
    };
  }
}

export const sharePointDataSourceInfoGenerator =
  new SharePointDataSourceInfoGenerator();
