/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 */

// Despite the path, this file is hand-edited, not generated. It is registered
// as a source in `packages/appgen-dev/src/data-modeling/sdk-file-reader.ts`
// with explicit import-replacement rules, and prior PRs (#1893) edited it by
// hand. A stale `"This file is autogenerated. Do not edit this file directly."`
// header was removed in this PR. Frozen snapshots under
// `packages/appgen-2026-*` retain the old header — also fine since they are
// date-pinned and not consumed at runtime here.

import type { DataClient } from '@microsoft/power-apps/data';
import { getClient } from '@microsoft/power-apps/data';
import { getDataSourcesInfo } from './data-source-info-generator';
import type { TableToTypescriptMapping } from './table-mapping-types';
import type { IAppGenDataClient, IOperationOptions, TableRow } from './types';
import { withRetry } from './withRetry';

// `JSON.stringify(err)` returns "{}" for Error instances and many SDK error
// shapes whose useful properties are non-enumerable. Surface a meaningful
// single-line message instead. Stack traces are preserved on the thrown
// `Error.cause`, not in the returned string.
const MAX_MESSAGE_LENGTH = 500;

// Scrub credential values from the JSON fallback — Axios `config.headers` is
// enumerable and would otherwise flow to telemetry. Pattern is intentionally
// substring-match (unanchored) so variants like `bearer_token`, `sessionid`,
// `X-API-Key`, `accessToken`, `userPwd` are all caught — do not anchor.
const SENSITIVE_KEY_PATTERN =
  /authorization|bearer|cookie|session|jwt|password|passwd|pwd|secret|token|credential|api[-_]?key/i;

// Strip Bearer-token-shaped values out of free-form message strings before
// they reach the joined output. The redactingReplacer scrubs by key name in
// the JSON fallback, but upstream services sometimes embed a token directly
// in their `message` text (e.g. `"Bearer eyJhbGc... rejected"`).
const BEARER_TOKEN_PATTERN = /Bearer\s+[A-Za-z0-9._\-+/=]+/gi;
function scrubBearerTokens(s: string): string;
function scrubBearerTokens(s: string | undefined): string | undefined;
function scrubBearerTokens(s: string | undefined): string | undefined {
  return s?.replace(BEARER_TOKEN_PATTERN, 'Bearer [REDACTED]');
}

function truncate(s: string): string {
  return s.length > MAX_MESSAGE_LENGTH
    ? s.slice(0, MAX_MESSAGE_LENGTH) + '…'
    : s;
}

function toStatusNumber(value: unknown): number | undefined {
  // Filter 0 — Axios uses it for network-level failures; the `code` field
  // (e.g. ECONNABORTED) carries the signal in those cases.
  if (typeof value === 'number' && value > 0) return value;
  if (typeof value === 'string' && /^\d+$/.test(value)) {
    const n = Number(value);
    return n > 0 ? n : undefined;
  }
  return undefined;
}

function toCodeString(value: unknown): string | undefined {
  if (typeof value === 'string') return value || undefined;
  if (typeof value === 'number') return String(value);
  return undefined;
}

function redactingReplacer(key: string, value: unknown): unknown {
  return key && SENSITIVE_KEY_PATTERN.test(key) ? '[REDACTED]' : value;
}

export function serializeClientError(err: unknown): string {
  if (err == null) return 'Unknown error';
  // String fast-path must still go through scrubBearerTokens — `err` is typed
  // `unknown`, so a caller can hand us a string containing `Bearer eyJ...`.
  if (typeof err === 'string') return truncate(scrubBearerTokens(err));
  if (typeof err !== 'object') return String(err);

  const e = err as Record<string, unknown>;
  const nested = e.error as { message?: unknown } | undefined;
  const response = e.response as
    | { status?: unknown; data?: unknown }
    | undefined;
  // AxiosError's `message` is generic ("Request failed with status code 400");
  // the Dataverse/OData detail lives at response.data.error.{message,code}.
  const odataError = (response?.data as { error?: unknown } | undefined)
    ?.error as { message?: unknown; code?: unknown } | undefined;

  const primaryMessage = scrubBearerTokens(
    (typeof e.message === 'string' && e.message) ||
      (nested && typeof nested.message === 'string'
        ? nested.message
        : undefined) ||
      // Some SDKs wrap a real Error in `err.error.message` instead of using
      // it as a string — peel one level if so.
      (nested?.message instanceof Error ? nested.message.message : undefined),
  );

  const odataMessage = scrubBearerTokens(
    odataError && typeof odataError.message === 'string' && odataError.message
      ? odataError.message
      : undefined,
  );

  const statusNum =
    toStatusNumber(e.status) ?? toStatusNumber(response?.status);

  // AxiosError's `code` (e.g. `ERR_BAD_REQUEST`, `ECONNABORTED`) and the
  // OData error's `code` (e.g. `0x80040220`) carry different signals — the
  // first is transport-level, the second is business-level. Emit both when
  // they're present and distinct.
  const primaryCode = toCodeString(e.code);
  const odataCode = toCodeString(odataError?.code);

  const parts = [
    primaryMessage,
    odataMessage !== primaryMessage ? odataMessage : undefined,
    statusNum !== undefined ? `HTTP ${statusNum}` : undefined,
    primaryCode,
    odataCode !== primaryCode ? odataCode : undefined,
  ].filter((part): part is string => Boolean(part));
  if (parts.length > 0) return truncate(parts.join(' | '));

  if (err instanceof Error) return truncate(err.name || 'Error');

  // JSON.stringify emits only enumerable properties — unlike
  // Object.getOwnPropertyNames, which would dump Axios `config.headers` etc.
  // Run the result through scrubBearerTokens too: redactingReplacer scrubs
  // by *key name*, but a Bearer token sitting under a non-sensitive key
  // (e.g. `{ description: 'Bearer eyJ... rejected' }`) would otherwise leak.
  try {
    const json = JSON.stringify(err, redactingReplacer);
    if (json && json !== '{}') return truncate(scrubBearerTokens(json));
  } catch {
    /* circular reference */
  }

  return truncate(scrubBearerTokens(String(err)));
}

export interface DataSourceClientConfig {
  /** Function to get the table identifier from metadata */
  getTableId: (tableMetadata: TableToTypescriptMapping) => string;
  /** Optional function to sanitize records before create operations */
  sanitizeRecordOnCreate?: (record: TableRow) => TableRow;
  /** Optional function to sanitize records before update operations */
  sanitizeRecordOnUpdate?: (record: TableRow) => TableRow;
}

export class AppGenByocDataClient implements IAppGenDataClient {
  private byocSdkClient: DataClient;
  private config?: DataSourceClientConfig;
  /**
   * @param config - data-source customization (table id resolver, sanitizers).
   * @param dataClient - **internal**: test-only injection seam. Production
   *   callers should omit this; the BYOC SDK client is constructed from
   *   `getDataSourcesInfo()` when not supplied.
   */
  public constructor(config?: DataSourceClientConfig, dataClient?: DataClient) {
    this.byocSdkClient = dataClient ?? getClient(getDataSourcesInfo());
    this.config = config;
  }

  private getTableId(tableMetadata: TableToTypescriptMapping): string {
    return (
      this.config?.getTableId(tableMetadata) ?? tableMetadata.apiDataTableId
    );
  }

  public async createRecordAsync(
    tableMetadata: TableToTypescriptMapping,
    record: TableRow,
  ): Promise<void> {
    return withRetry(
      async () => {
        const sanitizedRecord = this.config?.sanitizeRecordOnCreate
          ? this.config.sanitizeRecordOnCreate(record)
          : record;
        const clientResult = await this.byocSdkClient.createRecordAsync<
          TableRow,
          TableRow
        >(this.getTableId(tableMetadata), sanitizedRecord);
        if (!clientResult.success) {
          throw new Error(serializeClientError(clientResult.error), {
            cause: clientResult.error,
          });
        }
      },
      'createRecordAsync',
      { maxAttempts: 1 },
    );
  }

  public async updateRecordAsync(
    tableMetadata: TableToTypescriptMapping,
    record: TableRow,
    recordId: string,
  ): Promise<void> {
    return withRetry(
      async () => {
        const sanitizedRecord = this.config?.sanitizeRecordOnUpdate
          ? this.config.sanitizeRecordOnUpdate(record)
          : record;
        const clientResult = await this.byocSdkClient.updateRecordAsync<
          TableRow,
          TableRow
        >(this.getTableId(tableMetadata), recordId, sanitizedRecord);
        if (!clientResult.success) {
          throw new Error(serializeClientError(clientResult.error), {
            cause: clientResult.error,
          });
        }
      },
      'updateRecordAsync',
      { maxAttempts: 1 },
    );
  }

  public async deleteRecordAsync(
    tableMetadata: TableToTypescriptMapping,
    recordId: string,
  ): Promise<void> {
    return withRetry(
      async () => {
        const clientResult = await this.byocSdkClient.deleteRecordAsync(
          this.getTableId(tableMetadata),
          recordId,
        );
        // The SDK may return success via clientResult.success (SharePoint) or
        // via a batch response payload data[0].status === 204 (Dataverse).
        // Accept either form so both connectors work correctly.
        // eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/no-unsafe-member-access
        const batchStatus = (clientResult.data as any)?.[0]?.status;
        if (!clientResult.success && batchStatus !== 204) {
          throw new Error(serializeClientError(clientResult.error), {
            cause: clientResult.error,
          });
        }
      },
      'deleteRecordAsync',
      { maxAttempts: 1 },
    );
  }

  public async retrieveRecordAsync(
    tableMetadata: TableToTypescriptMapping,
    recordId: string,
  ): Promise<TableRow> {
    return withRetry(async () => {
      const clientResult =
        await this.byocSdkClient.retrieveRecordAsync<TableRow>(
          this.getTableId(tableMetadata),
          recordId,
          undefined,
        );
      if (!clientResult.success) {
        throw new Error(serializeClientError(clientResult.error), {
          cause: clientResult.error,
        });
      }
      return clientResult.data;
    }, 'retrieveRecordAsync');
  }

  public async retrieveMultipleRecordsAsync(
    tableMetadata: TableToTypescriptMapping,
    options?: IOperationOptions,
  ): Promise<TableRow[]> {
    return withRetry(async () => {
      const clientResult =
        await this.byocSdkClient.retrieveMultipleRecordsAsync<TableRow>(
          this.getTableId(tableMetadata),
          options,
        );
      if (!clientResult.success) {
        throw new Error(serializeClientError(clientResult.error), {
          cause: clientResult.error,
        });
      }
      return clientResult.data;
    }, 'retrieveMultipleRecordsAsync');
  }

  public requiresFullRowForUpdate(): boolean {
    return false;
  }
}
