/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import type { ColumnDataType, TableRow, TableSchemaMetadata } from './types';

export interface LocalData {
  apiMetadataTableId: string;
  data: TableRow[];
}

export interface DataModelConfig {
  id: string;
  iterationId: string;
  updateInProgress?: boolean;
  tableMappings: TableToTypescriptMapping[];
  dataModel?: TableSchemaMetadata;
  useLocalData?: boolean;
  enableInMemoryDataAtRuntime?: boolean;
  dataSdkVersion?: string;
}

export type DataSourceType = 'InMemory' | 'Dataverse' | 'SharePoint';

export type ByocSdkDataSchema = object;

export interface ChoiceColumnToTypescriptOptionSetMetadata {
  options: Array<{
    label: string;
    typescriptValue: string;
    apiValue: number | string;
  }>;
  optionSetTypeScriptEnumName: string;
  optionSetTypeScriptEnumTypeName: string;
}

export interface CommonLookupMetadata {
  targetTableApiMetadataTableId: string;
  alternateTargetTableDataSourceType: DataSourceType;
}

export type PropertyJsDocs = Record<
  string,
  string | number | boolean | undefined
>;

/**
 * Validation constraints for a column that can be used to generate Zod schemas
 * and form validation rules
 */
export interface CommonValidationMetadata {
  /** Minimum numeric value (for numeric types) */
  minValue?: number;
  /** Maximum numeric value (for numeric types) */
  maxValue?: number;
  /** Maximum string length (for text types) */
  maxLength?: number;
  /** Decimal precision (for decimal/double types) */
  precision?: number;
  /** Date format regex validation (for date types) */
  dateRegex?: {
    pattern: string;
    message: string;
  };
  /** ID validation type - 'string' for SharePoint, 'guid' for Dataverse */
  idValidationType?: 'string' | 'guid';
}

export interface BaseColumnToTypescriptMapping {
  apiPropertyName: string;
  apiPropertyNameCaseSensitive: string;
  displayName: string;
  typescriptPropertyName: string;
  isPrimaryName: boolean;
  isPrimaryId: boolean;
  isRequired: boolean;
  propertyJsDocs: PropertyJsDocs;
  validationMetadata: CommonValidationMetadata;
}

export interface LookupColumnToTypescriptMapping extends BaseColumnToTypescriptMapping {
  type: 'Lookup';
  lookupMetadata: CommonLookupMetadata; // Required
}

export interface ChoiceColumnToTypescriptMapping extends BaseColumnToTypescriptMapping {
  type: 'Choice' | 'Choices';
  optionSetMetadata: ChoiceColumnToTypescriptOptionSetMetadata;
}

export interface RegularColumnToTypescriptMapping extends BaseColumnToTypescriptMapping {
  type: Exclude<ColumnDataType, 'Lookup' | 'Choice' | 'Choices'>;
  lookupMetadata?: undefined;
  optionSetMetadata?: undefined;
}

export type ColumnToTypescriptMapping =
  | LookupColumnToTypescriptMapping
  | ChoiceColumnToTypescriptMapping
  | RegularColumnToTypescriptMapping;

export interface TableToTypescriptMapping {
  dataSourceKey: string;
  schemaFileName: string;
  dataSourceType: DataSourceType;
  schema?: ByocSdkDataSchema;
  apiDataTableId: string;
  apiMetadataTableId: string;
  typescriptModelInterfaceName: string;
  initialData?: TableRow[];
  powerConfigData?: PowerAppsRepoConfig;
  typescriptServiceClassName: string;
  modelFileName: string;
  serviceFileName: string;
  hookFileName: string;
  validatorFileName: string;
  columns: ColumnToTypescriptMapping[];
}

export interface GetTableMetadataOptions {
  dataSourceName?: string;
  apiDataTableId?: string;
  apiMetadataTableId?: string;
  markErrorAsExpectedIfNotFound?: boolean;
}

interface DataverseDataSource {
  entitySetName: string;
  logicalName: string;
  isHidden: boolean;
}

interface DataSet {
  dataSources: Record<string, { tableName: string }>;
}

interface ConnectionReference {
  id: string;
  displayName: string;
  dataSources: string[];
  authenticationType?: string | null;
  sharedConnectionId?: string | null;
  dataSets?: Record<string, DataSet>;
  xrmConnectionReferenceLogicalName?: string | undefined;
}

export interface DatabaseReference {
  state: string;
  instanceUrl?: string;
  webApiVersion?: string;
  dataSources: Record<string, DataverseDataSource>;
  version: string;
  environmentVariableName?: string;
}

export const initialPowerAppsRepoConfigData: Pick<
  PowerAppsRepoConfig,
  'connectionReferences' | 'databaseReferences'
> = {
  connectionReferences: {},
  databaseReferences: {},
};

export interface PowerAppsRepoConfig {
  appId?: string;
  appDisplayName?: string;
  description?: string | null;
  environmentId?: string;
  buildPath?: string;
  buildEntryPoint?: string;
  logoPath?: string;
  localAppUrl?: string;
  connectionReferences?: Record<string, ConnectionReference>;
  databaseReferences?: Record<string, DatabaseReference>;
}
