/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { getDataModelConfig } from './data-model-config-accessor';
import type {
  ColumnToTypescriptMapping,
  DataSourceType,
  GetTableMetadataOptions,
  TableToTypescriptMapping,
} from './table-mapping-types';
import type { ColumnDataType } from './types';

export interface DataModelConfigForLog {
  updateInProgress?: boolean;
  dataModelConfigId: string;
  dataModelConfigIterationId: string;
  dataSdkVersion?: string;
  tableMappings: GetTableMetadataSummaryResult;
}

export type GetTableMetadataSummaryResult = Array<{
  dataSourceType: DataSourceType;
  typescriptModelInterfaceName: string;
  apiMetadataTableId: string;
  apiDataTableId: string;
  columns: Array<{
    type: ColumnDataType;
    typescriptPropertyName: string;
    apiPropertyName: string;
    isPrimaryName: boolean;
    isPrimaryId: boolean;
    isRequired: boolean;
  }>;
}>;

export function getDataModelConfigForLog(): DataModelConfigForLog {
  const dataModelConfig = getDataModelConfig(false);

  return {
    updateInProgress: dataModelConfig.updateInProgress,
    dataModelConfigId: dataModelConfig.id,
    dataModelConfigIterationId: dataModelConfig.iterationId,
    dataSdkVersion: dataModelConfig.dataSdkVersion,
    tableMappings: getTableToTypescriptMappingForLog(
      dataModelConfig.tableMappings,
    ),
  };
}

export function getTableToTypescriptMappingForLog(
  tables: TableToTypescriptMapping[],
): GetTableMetadataSummaryResult {
  return tables.map((table) => {
    return {
      dataSourceType: table.dataSourceType,
      typescriptModelInterfaceName: table.typescriptModelInterfaceName,
      apiMetadataTableId: table.apiMetadataTableId,
      apiDataTableId: table.apiDataTableId,
      columns: table.columns.map((column) => {
        const additionalMetadata: Record<string, string> = {};

        if (column.type === 'Lookup') {
          additionalMetadata.targetTableApiMetadataTableId =
            column.lookupMetadata.targetTableApiMetadataTableId;
        } else if (column.type === 'Choices' || column.type === 'Choice') {
          additionalMetadata.optionSetTypeScriptEnumName =
            column.optionSetMetadata.optionSetTypeScriptEnumName;
          additionalMetadata.optionSetTypeScriptEnumTypeName =
            column.optionSetMetadata.optionSetTypeScriptEnumTypeName;
        }

        return {
          type: column.type,
          typescriptPropertyName: column.typescriptPropertyName,
          apiPropertyName: column.apiPropertyName,
          isPrimaryName: column.isPrimaryName,
          isPrimaryId: column.isPrimaryId,
          isRequired: column.isRequired,
          additionalMetadata,
        };
      }),
    };
  });
}

export async function getTableMetadata(
  options: GetTableMetadataOptions,
): Promise<TableToTypescriptMapping> {
  const dataModelConfig = getDataModelConfig();
  let tableMetadata: TableToTypescriptMapping | undefined;
  if (options.dataSourceName) {
    tableMetadata = dataModelConfig.tableMappings.find(
      (x) => x.typescriptModelInterfaceName === options.dataSourceName,
    ) as TableToTypescriptMapping | undefined;
  } else if (options.apiDataTableId) {
    tableMetadata = dataModelConfig.tableMappings.find(
      (x) => x.apiDataTableId === options.apiDataTableId,
    ) as TableToTypescriptMapping | undefined;
  } else if (options.apiMetadataTableId) {
    tableMetadata = dataModelConfig.tableMappings.find(
      (x) => x.apiMetadataTableId === options.apiMetadataTableId,
    ) as TableToTypescriptMapping | undefined;
  }

  if (!tableMetadata) {
    throw new Error(
      `No table metadata was found for '${JSON.stringify({ options, tableMetadataIsNotInSyncWithSource: options.markErrorAsExpectedIfNotFound })}'`,
    );
  }

  return tableMetadata;
}

export interface TargetTableMetadata {
  targetTableMetadata: TableToTypescriptMapping;
  primaryIdColumnMapping: ColumnToTypescriptMapping;
  primaryNameColumnMapping: ColumnToTypescriptMapping;
}

export interface GetTargetTableMetadataOptions {
  targetTableApiMetadataTableId: string;
}

export function getColumn(
  tableMetadata: TableToTypescriptMapping,
  apiPropertyName: string,
): ColumnToTypescriptMapping {
  const column = tableMetadata.columns.find(
    (x) => x.apiPropertyName === apiPropertyName,
  );
  if (!column) {
    throw new Error(
      `No column found for API property name '${apiPropertyName}' in table '${tableMetadata.apiMetadataTableId}'`,
    );
  }
  return column;
}

export function getPrimaryNameColumn(
  tableMetadata: TableToTypescriptMapping,
): ColumnToTypescriptMapping {
  const primaryColumn = tableMetadata.columns.find((x) => x.isPrimaryName);
  if (!primaryColumn) {
    throw new Error(
      `No primary name column found for table '${tableMetadata.apiMetadataTableId}'`,
    );
  }
  return primaryColumn;
}

export function getPrimaryIdColumn(
  tableMetadata: TableToTypescriptMapping,
): ColumnToTypescriptMapping {
  const primaryColumn = tableMetadata.columns.find((x) => x.isPrimaryId);
  if (!primaryColumn) {
    throw new Error(
      `No primary id column found for table '${tableMetadata.apiMetadataTableId}'`,
    );
  }
  return primaryColumn;
}

export async function getTargetTableMetadata(
  options: GetTargetTableMetadataOptions,
): Promise<TargetTableMetadata> {
  const targetTableMetadata = await getTableMetadata({
    apiMetadataTableId: options.targetTableApiMetadataTableId,
  });
  if (!targetTableMetadata) {
    throw new Error(
      `Failed to retrieve metadata for table with API Metadata Table ID: ${options.targetTableApiMetadataTableId}`,
    );
  }

  const primaryIdColumnMapping = getPrimaryIdColumn(targetTableMetadata);
  const primaryNameColumnMapping = getPrimaryNameColumn(targetTableMetadata);

  return {
    targetTableMetadata,
    primaryIdColumnMapping,
    primaryNameColumnMapping,
  };
}

export function getPrimaryIdApiPropertyName(
  tableMetadata: TableToTypescriptMapping,
): string {
  const primaryIdColumn = getPrimaryIdColumn(tableMetadata);
  return primaryIdColumn.apiPropertyName;
}
