/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { withRpcError } from '../../rpc/exception';
import { getRpcClient } from '../../rpc-client';
import type { TableToTypescriptMapping } from '../common/table-mapping-types';
import type {
  IAppGenDataClient,
  IOperationOptions,
  TableRow,
} from '../common/types';

export class AppGenInMemoryDataClient implements IAppGenDataClient {
  public createRecordAsync(
    tableMetadata: TableToTypescriptMapping,
    record: TableRow,
  ): Promise<void> {
    return withRpcError(async () => {
      await getRpcClient().call<TableRow>('createRecordAsync', [
        { tableName: tableMetadata.apiMetadataTableId, record },
      ]);
    });
  }

  public updateRecordAsync(
    tableMetadata: TableToTypescriptMapping,
    record: TableRow,
    recordId: string,
  ): Promise<void> {
    return withRpcError(async () => {
      await getRpcClient().call<TableRow>('updateRecordAsync', [
        {
          tableName: tableMetadata.apiMetadataTableId,
          recordId,
          changes: record,
        },
      ]);
    });
  }

  public deleteRecordAsync(
    tableMetadata: TableToTypescriptMapping,
    recordId: string,
  ): Promise<void> {
    return withRpcError(async () => {
      await getRpcClient().call('deleteRecordAsync', [
        { tableName: tableMetadata.apiMetadataTableId, recordId },
      ]);
    });
  }

  public retrieveRecordAsync(
    tableMetadata: TableToTypescriptMapping,
    recordId: string,
  ): Promise<TableRow> {
    return withRpcError(async () => {
      const row = await getRpcClient().call<TableRow | undefined>(
        'retrieveRecordAsync',
        [{ tableName: tableMetadata.apiMetadataTableId, recordId }],
      );
      if (!row) {
        throw new Error(
          `The row with id ${recordId} was not found, for table: ${tableMetadata.apiMetadataTableId}.`,
        );
      }

      return row;
    });
  }

  public retrieveMultipleRecordsAsync(
    tableMetadata: TableToTypescriptMapping,
    options?: IOperationOptions,
  ): Promise<TableRow[]> {
    return withRpcError(async () => {
      return getRpcClient().call<TableRow[]>('retrieveMultipleRecordsAsync', [
        {
          tableName: tableMetadata.apiMetadataTableId,
          options,
        },
      ]);
    });
  }

  public requiresFullRowForUpdate(): boolean {
    return true;
  }
}
