/* eslint-disable eslint-comments/no-restricted-disable */
/* eslint-disable */

/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import type {
  RpcMessage,
  RpcMessageHandler,
  RpcMessageListenerCallback,
  RpcRequestMessage,
  RpcResponseMessage,
} from './rpc';

type WindowRpcMessageSerializer = (rpcMessage: RpcMessage) => any;
type WindowRpcMessageDeserializer = (message: any) => RpcMessage;

interface WindowPostMessageRpcHandlerOptions {
  targetWindow: Window;
  sourceWindow?: Window;
  messageSerializer?: WindowRpcMessageSerializer;
  messageDeserializer?: WindowRpcMessageDeserializer;
}

interface WindowPostMessageRpcHandlerOptionsInternal {
  targetWindow: Window;
  sourceWindow: Window;
  messageSerializer: WindowRpcMessageSerializer;
  messageDeserializer: WindowRpcMessageDeserializer;
}

export class WindowPostMessageRpcHandler implements RpcMessageHandler {
  private _listeners: any = {};
  private _options: WindowPostMessageRpcHandlerOptionsInternal;

  constructor(options: WindowPostMessageRpcHandlerOptions) {
    if (!options) {
      throw new Error('options required');
    }

    if (!options.targetWindow) {
      throw new Error('targetWindow required');
    }

    this._options = {
      sourceWindow: window,
      messageSerializer: (rpcMessage) => rpcMessage,
      messageDeserializer: (data) => data as RpcMessage,
      ...options,
    };
  }

  public postMessage(rpcMessage: RpcMessage, targetOrigin: string): void {
    this._options.targetWindow.postMessage(
      this._options.messageSerializer(rpcMessage),
      targetOrigin,
    );
  }

  public addListener(listener: RpcMessageListenerCallback): void {
    if (this._listeners[listener as any]) {
      console.error('duplicate rpc listener added');
    }

    this._listeners[listener as any] = (e: any) => {
      const data = this._options.messageDeserializer(e.data) as any;
      if (!data) {
        return;
      } else if (data.method) {
        listener({
          signature: data.signature,
          id: data.id,
          method: data.method,
          params: data.params,
        } as RpcRequestMessage);
      } else {
        listener({
          signature: data.signature,
          id: data.id,
          result: data.result,
          error: data.error,
        } as RpcResponseMessage);
      }
    };

    this._options.sourceWindow.addEventListener(
      'message',
      this._listeners[listener as any],
    );
  }

  public removeListener(listener: RpcMessageListenerCallback): void {
    this._options.sourceWindow.removeEventListener(
      'message',
      this._listeners[listener as any],
    );
    delete this._listeners[listener as any];
  }
}
