/*!
 * Copyright (C) Microsoft Corporation. All rights reserved.
 * This file is autogenerated. Do not edit this file directly.
 */

import { Rpc } from './rpc/rpc';
import { WindowPostMessageRpcHandler } from './rpc/window-post-message-rpc-handler';

let rpcClient: Rpc | null = null;
export function getRpcClient(): Rpc {
  if (!rpcClient) {
    rpcClient = new Rpc({
      friendlyName: 'In Memory Data Provider',
      signature: 'data-agent-provider',
      targetOrigin: '*',
      rpcMessageHandler: new WindowPostMessageRpcHandler({
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
        targetWindow: window.top!,
      }),
    });
    // eslint-disable-next-line @typescript-eslint/no-floating-promises
    rpcClient.ack();
  }
  return rpcClient;
}
